### ISSUE TITLE
UnicodeDecodeError raised when reading some UFF/UNV files

### ISSUE THREAD

**Issue by chsafouane** [openmodal/pyuff#10]
Pyuff  outputs this error (see attached image) when trying to read some files(while it works well for some other files with other kind of data). Is there a way to solve this issue?

![capture](https://user-images.githubusercontent.com/31566323/38832089-c28d5216-41c1-11e8-94b4-763ff7bacca8.PNG)

**Comment by jankoslavic** [comment]
You have probably some non ASCII characters in your file. Please share the file, so I can look into detail.

**Comment by chsafouane** [comment]
As github doesn't allow file deletion, I've just sent the file to your mail address janko.slavic@gmail.com. Thank you !

**Comment by jankoslavic** [comment]
I have looked into the file and it does not have a properly closed section (line with "    -1")
