### ISSUE TITLE
Overflow error when loading large uff file

### ISSUE THREAD

**Issue by FrederickPurcell** [openmodal/pyuff#15]
when loading large uff file (4gb and larger) overflow errors were being raised in the refresh function as the indices of the start and end values (i.e. '-1') were larger then 2**31. This issue is fixed by changing 'dtype=int' to 'dtype=int64' in lines 377 and 390 of pyuff.py. This change should give capacity to deal with larger folders and hopefully not have any downsides?

**Comment by jankoslavic** [comment]
Thank you @FrederickPurcell this was an easy update! v1.19 is already on pypi.

Upgrade: pip install pyuff --upgrade
