### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc5' in file setup.py on line 2, but no encoding declared

### ISSUE THREAD

**Issue by nilswagner** [openmodal/pyuff#16]
python setup.py develop --install-dir $HOME/local
fails with the above mentioned error message.
Therefore

# -*- coding: utf-8 -*-

should be added to pyuff.py and setup.py

**Comment by jankoslavic** [comment]
Hi @nilswagner! Which version of python are you using?

**Comment by jankoslavic** [comment]
I am closing this issue as this should not be a problem with Python 3 where everything is unicode encoded (http://lucumr.pocoo.org/2014/5/12/everything-about-unicode/)
