### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 705: ordinal not in range(128)

### ISSUE THREAD

**Issue by nilswagner** [openmodal/pyuff#17]
pyuff.py", line 1372, in _extract58
split_data = blockData.decode('ascii').splitlines(True)[13:]

**Comment by nilswagner** [comment]
The problem is caused by a unicode character in the header (see below)
    -1
    58
ref8_1                                                                          
NONE                                                                            
24-Mar-17 18:16:12                                                              
Record 1 of Dataset no 58                                                       
H1 : #  2 / #  1                                                                
    4         0    0         0 NONE               0   0 NONE               0   0
         5     12801         1 0.00000e+00  1.95313e-01  0.00000e+00 
        18    0    0    0 NONE                 Hz                  
         1    0    0    0 Frequency Function   (1/N)*(m/s²)

**Comment by jankoslavic** [comment]
dear @nilswagner please check the last commit if it works with your data; I have made the necessary changes and all the test have passed. Please confirm it works also for you. You can also provide me with a test file snipped and I will include it in the test list

**Comment by nilswagner** [comment]
Dear Janko,
Your last commit doesn't resolve the issue. 
    split_data = blockData.decode('utf-8').splitlines(True)[13:]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 705: invalid start byte
[janko.txt](https://github.com/openmodal/pyuff/files/2464044/janko.txt)

**Comment by jankoslavic** [comment]
Thank you @nilswagner for the feedback. Will try to get to this ASAP

**Comment by jankoslavic** [comment]
Dear @nilswagner I have added the test file; few additional changes were needed. The tests are passing. I ask you to double-check the implementation.

**Comment by nilswagner** [comment]
Great. Works fine for me.
Thank you very much!

**Comment by jankoslavic** [comment]
The version 1.20 is now also on pypi
