### ISSUE TITLE
ValueError during `UFF.read_sets()` (type 58) when last line of set contains trailing space characters

### ISSUE THREAD

**Issue by dsholes** [openmodal/pyuff#20]
I have a .uff file with multiple sets. The last line of certain sets contains space characters:
```
['  1.99130E+03  7.92753E-03 -3.55791E-10  1.99274E+03  7.57201E-03 -8.85350E-10  \n',
 '  1.99418E+03  7.48720E-03 -3.93900E-11  1.99562E+03  7.53958E-03 -1.48228E-10  \n',
 '  1.99724E+03  7.36270E-03 -1.28388E-10  1.99868E+03  7.44406E-03  4.39329E-11  \n',
 '  2.00000E+03  7.45827E-03  5.00480E-10                                         \n']
```
Thus, line 1372 of pyuff fails with a ValueError because it's failing to convert these space characters to a float:
`values.extend([float(line[13 * i:13 * (i + 1)]) for i in range(len(line) // 13)])`

I'm currently using this as a temporary fix:
```
for line in split_data:  # '6E13.5'
     try:
          values.extend([float(line[13 * i:13 * (i + 1)]) for i in range(len(line) // 13)])
     except ValueError as e:
          line = line.rstrip() + "\n"
```
But I wanted to alert you to the issue and ask if anyone has a better idea for how to handle this error?

By the way, I believe the .uff files are being output from [SignalStar Scalar](http://www.dataphysics.com/products-and-solutions/vibration-controllers-signalstar/signalstar-scalar.html) developed by DataPhysics.

**Comment by jankoslavic** [comment]
please provide a snippet test file and I will take a look

**Comment by dsholes** [comment]
Thanks for the quick response. Let me know if you need anything else:
[test_snippet.zip](https://github.com/openmodal/pyuff/files/2572161/test_snippet.zip)

**Comment by jankoslavic** [comment]
Hi @dsholes I have looked into the details now. This file does not look like a good test case/example. The line should not end with spaces. Further, there are two additional issue with this file: the `Function Type` is "unknown or general" and the and the `data case` is 2 which means that single precision is used for all data. This is very inaccurate and due to this pyuff supports only double (it can read single, but writes always double). I was considering adding rstrip to every read, but this opens new issues with other files... exception handling also does not look good to me...
Any further ideas? What do you think?

**Comment by dsholes** [comment]
Hi @jankoslavic,

Thank you for looking into it. Unfortunately I am not familiar with proper formatting of UFF files. If you believe that the issues I described are formatting issues with the file itself, then you can close this issue.

I imagine this is a very particular case, perhaps only related to this SignalStar Scalar software. It is commercial software, however, so others may encounter a similar issue in the future. For now, I'll keep my temporary solution, as it works for my basic purposes of importing and plotting this particular UFF data.

**Comment by jankoslavic** [comment]
Hi @dsholes thank you for understanding; I will close this issue and maybe we will come back to it later.

**Comment by Fesert2017** [comment]
Hello,

I would like to recover this topic. I found the same issue when reading a *.uff file. The last line of certain sets contains space characters and this leads to a UFFException. I am not sure what is the software used to ouput this data but that is something that I can consult.

Here is the code example:

[example_error.zip](https://github.com/openmodal/pyuff/files/2922091/example_error.zip)

In this case, the Function Type is also "General or Unknown" although it should be "Spectrum" and the Data Type is "complex, single precision".

It seems that this "space characters" error is quite common. Do you think it is worth to handle it?

**Comment by jankoslavic** [comment]
Hi @Fesert2017 !

I have checked the uff file you provided. It is single precision file (e.g. 5.01443E-01). I would not suggest using such bad precision; the pyUFF development is focused on double-precision. 

Please check if you can export to double precision. If you are not able to do so, I suggest to use the `rstrip` solution above.

I hope this helps you.

**Comment by Fesert2017** [comment]
Hi @jankoslavic ,

Thank you very much for your prompt response !! I would suggest my supplier to export data with double precision and in the mean time I will implement the `rstrip` solution. If I find out another possible error handling solution I will let you know. Regards !
