### ISSUE TITLE
uff files written and read back in do not match content

### ISSUE THREAD

**Issue by PapaTim68** [openmodal/pyuff#21]
If a uff file is written using this module with this dict as part of the input list:
```
{'type': 58,..., 'id5': 'PF-I-0301y+ [g]', 'func_type': 12, 'func_id': 25, 'ver_num': 1, 'load_case_id': 0, 'rsp_ent_name': 'PF-I-0301y+', ...}
```
the file generated for this item looks like this:
```
    -1
    58                                                                          
                                                                                
Runn_xxx                                                                        
25/03/19                                                                        
Sine; 1 g                                                                       
PF-I-0301y+ [g]                                                                 
   12        25    1         0 PF-I-0301y+         0   0       NONE         0   0
         6       284         0   0.0000e+00   0.0000e+00   0.0000e+00
        18    0    0    0 Frequenz             Hz                  
        12    1    0    0 Acceleration         g                   
         0    0    0    0 NONE                 NONE                
         0    0    0    0 NONE                 NONE  
```
NOTE: The 7th line is longer than the others and also longer than the 80chars that it is supposed to be.
if the uff file is read back in a different dict entry is generated for this item:
```
{'type': 58, ..., 'id5': 'PF-I-0301y+ [g]', 'func_type': 12, 'func_id': 25, 'ver_num': 1, 'load_case_id': 0, 'rsp_ent_name': 'PF-I-0301y', ...}
```
So the Problem is that the second entry should match the first one, but it doesnt.
The question is now if this behavior is intended or if the module should account for this Problem?

**Comment by jankoslavic** [comment]
Dear @PapaTim68 can you please prepare a snippet file and I will try to figure out what is going on.

**Comment by PapaTim68** [comment]
Here is an examaple script note that the module is modified a little bit in order to support function type 12
which shouldnt interefere with this
[pyNastran-master.zip](https://github.com/openmodal/pyuff/files/3019063/pyNastran-master.zip)

**Comment by jankoslavic** [comment]
Hi @PapaTim68! I ask you for a snippet:
https://en.wikipedia.org/wiki/Snippet_(programming)
This means minimal code to reproduce your problem.

**Comment by PapaTim68** [comment]
Yeah that is technically what that code does ...
