### ISSUE TITLE
writing of 58 dataset, n_bytes should be multiplied by 2 for real valued dataset

### ISSUE THREAD

**Issue by niels4911** [openmodal/pyuff#23]
In pyuff version 1.20, pyuff.py line 892, 
nBytes = numPts * 4 should be changed to 
nBytes = numPts * 8, 

because ord_data_type = 4 is double precision

**Comment by jankoslavic** [comment]
This makes sense!
https://github.com/openmodal/pyuff/blob/a948cb29da99dc3dabc6459f5edeabe02f7965f4/pyuff.py#L878

it looks like the current binary test files are ord_data_type=2 and this error was not detected. @niels4911 can you please provide a snippet test file for testing?

**Comment by niels4911** [comment]
I'm kind of a newbee can you provide some info on how to this?

**Comment by jankoslavic** [comment]
You can send the snippet uff file to me via email :)

**Comment by niels4911** [comment]
OK here is a script that writes a binary uff, read it back and checks the n_bytes

[write_uff_test_nbytes.zip](https://github.com/openmodal/pyuff/files/3225632/write_uff_test_nbytes.zip)

**Comment by jankoslavic** [comment]
It took me few days to come back to this issue... there were additional changes required. it should work now and all the test are passing.

The commit:
https://github.com/openmodal/pyuff/commit/05ebdffdf739f88bb521409164ee6c097e730447

@niels4911 can you please double check before I send it to pypi?

**Comment by niels4911** [comment]
I have tried the new version, nbytes are now as expected.  

problem fixed. Thanks!
