### ISSUE TITLE
Test function for dataset 55 i.e. pyuff.prepare_test_55()

### ISSUE THREAD

**Issue by nilswagner** [openmodal/pyuff#24]
A test function for dataset 55 is currently missing in pyuff.

**Comment by nilswagner** [comment]
https://github.com/openmodal/pyuff/pull/25

**Comment by nilswagner** [comment]
A separate test like test_15.py or test_58.py and a corresponding *.uff within the data directory of pyuff would be nice.

**Comment by jankoslavic** [comment]
Hi @nilswagner this is a great proposal. Thanks. I can help implement it.

**Comment by nilswagner** [comment]
https://github.com/openmodal/pyuff/pull/26#issuecomment-535402305

**Comment by jankoslavic** [comment]
in the version 1.22 this issue is resolved
