### ISSUE TITLE
Support of additional datasets, i.e. 2411, 2412, 2420

### ISSUE THREAD

**Issue by nilswagner** [openmodal/pyuff#27]
The current dataset for coordinate systems (obsolete is 18) is
http://sdrl.uc.edu/sdrl/referenceinfo/universalfileformats/file-format-storehouse/universal-dataset-number-2420

As a result of surface measurements it might be useful to support
http://sdrl.uc.edu/sdrl/referenceinfo/universalfileformats/file-format-storehouse/universal-dataset-number-2412

The current dataset for nodes (obsolete is 15) is
http://sdrl.uc.edu/sdrl/referenceinfo/universalfileformats/file-format-storehouse/universal-dataset-number-2411

**Comment by jankoslavic** [comment]
This would be nice to have! Anyone prepared to take on this issue?

**Comment by jankoslavic** [comment]
Dear @nilswagner ! I looks like there is no interest for this issue; I will close it for now.
