### ISSUE TITLE
Computation of real normal modes from complex eigenvectors

### ISSUE THREAD

**Issue by nilswagner** [openmodal/pyuff#28]
@jankoslavic 

Details are given in the papers by

S. R. Ibrahim
Computation of Normal Modes from Identified Complex Modes
AIAA JOURNAL, VOL. 21, NO. 3

and 

Ulrich Fuellekrug
Computation of real normal modes from complex eigenvectors
Mechanical Systems and Signal Processing 22 (2008) 57–65

**Comment by jankoslavic** [comment]
This looks more a modal identification issue. I would suggest to add this to pyema.
If modal parameters are identified, the pyema can have a method to conversion..

Can you please open it there?
https://github.com/ladisk/pyEMA/issues/new

Janko

**Comment by nilswagner** [comment]
Done.
