### ISSUE TITLE
Import time histories with number of points not multiple of 6 raise error

### ISSUE THREAD

**Issue by mglesser** [openmodal/pyuff#29]
.uff files of time histories with number of points that is not a multiple of 6, have a last line with 1 to 5 values only for each dataset. When trying to read such a file an error is raised at line 1367 of pyuff.py. It is caused by "float" trying to convert an empty string to float. 

A quick (but potentially ugly, I'm far from a Python expert) fix is to replace line 1367 by:

```python
for i in range(len(line) // 13):  
    if (line[13 * i:13 * (i + 1)] != '             '):  
        values.extend([float(line[13 * i:13 * (i + 1)])])
```

**Comment by jankoslavic** [comment]
DEar Martin!

Could you please provide also a test file, so it can be added to tests?
REgards,
Janko

**Comment by mglesser** [comment]
Dear Janko,
Please find below a .uff file that can be used to reproduce the issue. I took a better look to the file and it seems that the issue comes from the fact that the software used to generate the .uff filled the last non-full data line with white spaces.
Best regards,
Martin

[time-history.zip](https://github.com/openmodal/pyuff/files/4608104/time-history.zip)

**Comment by jankoslavic** [comment]
Dear Martin! I implemented a slightly numerically better implementation:
```
                    for line in split_data[:-1]:  # '6E13.5'
                        values.extend([float(line[13 * i:13 * (i + 1)]) for i in range(len(line) // 13)])
                    else:
                        line = split_data[-1]
                        values.extend([float(line[13 * i:13 * (i + 1)]) for i in range(len(line) // 13) if line[13 * i:13 * (i + 1)]!='             '])
```
it is on pypi. please upgrade

**Comment by mglesser** [comment]
Thanks a lot, Janko
