### ISSUE TITLE
Dataset 2412 handling

### ISSUE THREAD

**Issue by mglesser** [openmodal/pyuff#34]
Dear contributors,
I've noticed that dataset 2412 is supported in pyuff but is actually scanned as a dataset 15. At least in the file I'm dealing with (I hope it is not too exotic), dataset 2412 corresponds to mesh elements rather then points and should be handled differently.

In the project I'm working for, I will have to handle dataset 2412 as elements. I'm considering to do it in a fork of pyuff. If I succeed, would you be intersted in a pull-request?

**Comment by jankoslavic** [comment]
Sure, please go on; you can count on my support. Regards.

**Comment by jankoslavic** [comment]
This is now implemented:) thanks @mglesser

**Comment by mglesser** [comment]
For me everything is solved. Thanks @jankoslavic for the support. Please reopen the issue if anything happens.
