### ISSUE TITLE
Parsing for '    -1' tags

### ISSUE THREAD

**Issue by Gruvington** [openmodal/pyuff#40]
Hi,

I noticed that the parsing for '    -1' tags can cause erroneous behaviour.

The particular case I encountered was when 'rsp_node' value in the UFF was equal to -1. The number of empty spaces before the -1 was sufficient to cause the rsp_node to be recognised as a '    -1' tag. 

I'm not sure if the UFF file format prohibits -1 values or if this could occur at other header items that have a value of -1. 

In any case, it seems like the parsing could be adjusted to only identify a tag at a position where the entire line is equal to  '    -1' and not at other points in the file where  '    -1' is present.

**Comment by jankoslavic** [comment]
@Gruvington thank you for this message. We are aware of this problem (https://github.com/openmodal/pyuff/issues/9), but I see no easy solution. Having -1 in rsp_node is not a good idea:(

**Comment by Gruvington** [comment]
Thanks for the very quick response. And apologies I did not see the that you had already identified the issue - I am new to github. I can see how the issue is complicated by the parsing of binary formatted files.

**Comment by jankoslavic** [comment]
Thank you for understanding. I will close this issue.
