### ISSUE TITLE
Error refreshing UFF file

### ISSUE THREAD

**Issue by Chetan21** [openmodal/pyuff#5]
I have a single UFF file of 1.02 GB and I am unable to read it using pyuff package. Followed the simple steps mentioned by you guys [here].(https://github.com/openmodal/pyuff/blob/master/pyuff%20Showcase.ipynb)

I am getting an error doing this:
`uff_file = pyuff.UFF('data/beam.uff')`

I am not sure where the problem is:
1. Formatting of file is correct/incorrect
2. File is too large (that is my guess)
3. Code problem in refresh() function

**Comment by jankoslavic** [comment]
If I understand you correctly, already the showcase is not working for you? Which version of Python are you using?

**Comment by Chetan21** [comment]
I am using Python version 2.7.7

I am unable to load the UFF file through this command `uff_file = pyuff.UFF('data/beam.uff')`

**Comment by jankoslavic** [comment]
I am sorry, but Python 2.7 is not supported.

**Comment by Chetan21** [comment]
Which version of Python should I use? I have tried Python 3.6.0 and I am stuck with this:

`data = fh.read().decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x86 in position 1066: ordinal not in range(128)`

**Comment by Chetan21** [comment]
Ok. My file is in UFF58 bin format. Header of this file contains some text like this:
`\{D‑×þCàG÷CàG÷Cú•ÜCçÈ¨C.— D0fBC˜¹Âºû¤AÙ§<Ãy$ÌÃÑQ†Ãe‰üÃhÍ“ÃÍ` 

This is actually the 13th line in the header. No idea what encoding format is this. Is it possible to change the encoding style while reading? Or, any other alternate solution to this problem?

**Comment by jankoslavic** [comment]
Hi @Chetan21 ! the uff58 binary is currently not supported! I will open an issue with regards to this!

**Comment by jankoslavic** [comment]
I am reopening this issue; binary should be supported via 58b. Can you provide a simple test case?

**Comment by Chetan21** [comment]
README page of this package has these lines:

`This module is part of the www.openmodal.com project and defines an UFF class to manipulate with the UFF (Universal File Format) files.

Read from and write of data-set types 151, 15, 55, **58**, **58b**, 82, 164 is supported.`

**Comment by Chetan21** [comment]
I apologize. I am not an expert in such kind of files. I am trying to read data from UFF58 file, convert and use it for data analysis. 

In future, if I learn more about it then I shall update it :).

Thanks!

**Comment by jankoslavic** [comment]
Can you please share (janko.slavic@fs.uni-lj.si) the file you are working on and I will try to see what is going on?

**Comment by duracell013** [comment]
Hello,

I'm facing the same issue trying to read UFF 58b files with Python 3.6.
It's working fine with UFF58 (ascii).

Thanks in advance for your help!
Stephan

**Comment by jankoslavic** [comment]
Dear Stephan!
Thank you for sharing. I would need a minimum example to reproduce the error.

**Comment by jankoslavic** [comment]
Dear @duracell013! Thank you for sharing the files with me; I have added them to the data folder and have also prepared tests. Inside tests folder you can see test_58 where a mixed (binary and ascii) dataset 58 is first written to the measurement.uff and then read. It works fine. Please check it out. @Chetan21 is it working now for you also?

**Comment by jankoslavic** [comment]
Resolved with commit d061802
