### ISSUE TITLE
BUG: if header contains "    -1" which is the separator between datasets, the data will not be read accuretelly

### ISSUE THREAD

**Issue by jankoslavic** [openmodal/pyuff#9]
separators are lines starting with `    -1`.  The current implementation separates dataset by searching "    -1" and it can find such text inside header.

The problem would be solved if all separating lines would be long 80 characters. But they are not always (some programs write 6 characters, some 80).

dataset separators are searched in line 367:
`                    ind = data.find(b'    -1',ind+1)`

this would resolve the issue for ascii files (but not for binary data type as there is no line feed character) 
`                    if ind==0 or data[ind-1]==10: # this is to prevent finding '    -1' inside data`
`                        blockInd.append(ind)`

Here is the data to reproduce the problem:
>    -1                                                                          
>    58                                                                          
>Comments .....
>                                                                                
>07-Dec-17 14:38:01                                                              
>Throughput                                                                      
>                                                                                
>    1         1    1         0 PWL Mic            1   1 NONE              -1   0
>         2   2508876         1  1.11858E-05  1.95312E-05  0.00000E+00
>        17    0    0    0 Time                 s                   
>        15    0    0    0 Sound Pressure       Pa                  
>         0    0    0    0 NONE                 NONE                
>         0    0    0    0 NONE                 NONE                
> -6.73633E-03 -4.45648E-03 -5.28105E-03  1.05771E-03  4.89754E-06  4.09781E-03
>  2.53365E-03  3.55293E-03  1.44602E-03 -6.39344E-04 -1.60777E-03 -8.45454E-03
> -5.57633E-03 -1.14573E-02 -7.65722E-03 -8.14119E-03 -7.96941E-03 -4.06761E-03
> -5.44376E-03 -1.98611E-04 -1.88861E-03  1.98462E-03  2.70225E-03  4.37073E-03
>  7.21978E-03  6.17038E-03  1.21836E-02  5.60413E-03  8.95167E-03  4.52705E-03
> -9.68515E-03 -1.01424E-02 -1.14160E-02 -9.86869E-03 -6.59099E-03 -4.85307E-03
>  6.32693E-04 -8.87904E-04  4.28284E-03  2.48453E-03  5.60006E-03  5.39653E-03
>    -1

Any ideas?

**Comment by matmr** [comment]
We could write an algo that checks all kinds of possible delimiters and then makes a decisions. That's the only way if we want to be able to import any uff file.

**Comment by jankoslavic** [comment]
The above proposal works fine for ASCII based pyuff (numerical cost is negligible); however, for binary data it is not working. Maybe we can check if the first occurrence of `    -1` is of length 80 and then search such a separator. What do you think?
